src/Presentation/Models/ProjectPackagesViewModel.cs
using Application.Dtos.FoodDtos;
using Application.Dtos.PackageDtos;
using Application.Dtos.ThirdPartyDtos;

namespace Presentation.Models;

public class ProjectPackagesViewModel
{
    public IEnumerable<DonorResponseDto>? Donors { get; set; }
    public IEnumerable<ReceiverResponseDto>? Receivers { get; set; }
    public IEnumerable<FoodResponseDto>? Foods { get; set; }
    public IEnumerable<PackageReceivedResponseDto>? PackagesReceived { get; set; }
    public IEnumerable<PackageSentResponseDto>? PackagesSent { get; set; }
}

src/Presentation/Controllers/DonorController.cs
using Application.Dtos.ThirdPartyDtos;
using Application.Interfaces.ThirdParty;
using Domain.Entities.ThirdPartyRegister;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models.DonorModels;

namespace Presentation.Controllers;

public class DonorController : Controller
{
    private readonly IDonorService _donorService;

    public DonorController(IDonorService donorService)
    {
        _donorService = donorService;
    }

    [HttpGet("/DonorCreate")]
    public IActionResult DonorCreate()
    {
        return View();
    }

    [HttpGet("DonorUpdate/{id:guid}")]
    public async Task<IActionResult> DonorUpdate(Guid id)
    {
        var viewModel = await _donorService.GetById(id);

        return View(viewModel);
    }

    [HttpGet("DonorDelete/{id:guid}")]
    public async Task<IActionResult> DonorDelete(Guid id)
    {
        await _donorService.Delete(id);

        return RedirectToAction("ProjectEntities", "Project");
    }


    [HttpPost("DonorNew")]
    public async Task<IActionResult> DonorNew(DonorFormViewModel formViewModel)
    {
        var dto = new DonorRequestDto
        {
            Name = new ThirdPartyName(formViewModel.Name!),
            IsCompany = formViewModel.IsCompany
        };

        await _donorService.Insert(dto);

        TempData["ConfirmationMessage"] = "Donor created successfully";

        return RedirectToAction("ProjectEntities", "Project");
    }

    [HttpPost("DonorUpdated")]
    public async Task<IActionResult> DonorUpdated(DonorFormViewModel formViewModel)
    {
        var dto = new DonorRequestDto
        {
            Name = new ThirdPartyName(formViewModel.Name!),
            IsCompany = formViewModel.IsCompany
        };
        var id = formViewModel.Id;
        await _donorService.Edit(id, dto);

        TempData["ConfirmationMessage"] = "Donor created successfully";
        return RedirectToAction("ProjectEntities", "Project");
    }
}

src/Presentation/Controllers/FoodController.cs
using Application.Dtos.FoodDtos;
using Application.Interfaces.Food;
using Domain.Entities.Food;
using Domain.Enums.Food;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Presentation.Models;
using Presentation.Models.FoodModels;

namespace Presentation.Controllers;

public class FoodController : Controller
{
    private readonly IFoodService _foodService;

    public FoodController(IFoodService foodService)
    {
        _foodService = foodService;
    }

    [HttpGet("/FoodCreate")]
    public IActionResult FoodCreate()
    {
        var stateViewModel = new StateViewModel
        {
            States = Enum.GetValues(typeof(State))
                .Cast<State>()
                .Select(s => new SelectListItem
                {
                    Text = s.ToString(),
                    Value = ((int)s).ToString()
                })
                .ToList()
        };
        return View(stateViewModel);
    }

    [HttpGet("FoodUpdate/{id:guid}")]
    public async Task<IActionResult> FoodUpdate(Guid id)
    {
        var foodDto = await _foodService.GetById(id);
        var stateOptions = Enum.GetValues(typeof(State))
            .Cast<State>()
            .Select(s => new SelectListItem
            {
                Text = s.ToString(),
                Value = ((int)s).ToString(),
                Selected = s == foodDto.State
            });

        var viewModel = new FoodUpdateViewModel
        {
            Food = foodDto,
            StateOptions = new SelectList(stateOptions, "Value", "Text")
        };

        return View(viewModel);
    }

    [HttpGet("FoodDelete/{id:guid}")]
    public async Task<IActionResult> FoodDelete(Guid id)
    {
        await _foodService.Delete(id);

        return RedirectToAction("ProjectEntities", "Project");
    }


    [HttpPost("FoodNew")]
    public async Task<IActionResult> FoodNew(FoodUpdateResponseViewModel updateResponseViewModel)
    {
        var dto = new FoodRequestDto
        {
            FoodName = new FoodName(updateResponseViewModel.FoodName!),
            State = updateResponseViewModel.State,
            IsPerishable = updateResponseViewModel.IsPerishable,
            ExpirationDate = updateResponseViewModel.ExpirationDate
        };

        await _foodService.Insert(dto);

        TempData["ConfirmationMessage"] = "Food created successfully";

        return RedirectToAction("ProjectEntities", "Project");
    }

    [HttpPost("FoodUpdated")]
    public async Task<IActionResult> FoodUpdated(FoodUpdateResponseViewModel formViewModel)
    {
        var dto = new FoodRequestDto
        {
            FoodName = new FoodName(formViewModel.FoodName!),
            State = formViewModel.State,
            IsPerishable = formViewModel.IsPerishable,
            ExpirationDate = formViewModel.ExpirationDate
        };
        var id = formViewModel.Id;
        await _foodService.Edit(id, dto);

        TempData["ConfirmationMessage"] = "Food created successfully";
        return RedirectToAction("ProjectEntities", "Project");
    }
}

src/Presentation/Controllers/PackageSentController.cs
using Application.Dtos.PackageDtos;
using Application.Interfaces.Food;
using Application.Interfaces.Package;
using Application.Interfaces.ThirdParty;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models.PackageSentModels;

namespace Presentation.Controllers;

public class PackageSentController : Controller
{
    private readonly IFoodService _foodService;
    private readonly IPackageSentService _packageSent;
    private readonly IReceiverService _receiverService;

    public PackageSentController(IPackageSentService packageSentService, IReceiverService receiverService,
        IFoodService foodService)
    {
        _packageSent = packageSentService;
        _receiverService = receiverService;
        _foodService = foodService;
    }

    [HttpGet("/PackageSentCreate")]
    public IActionResult PackageSentCreate()
    {
        var viewModel = new PackageSentViewModels
        {
            Receivers = _receiverService.GetAll(),
            Foods = _foodService.GetAll()
        };
        return View(viewModel);
    }

    [HttpGet("PackageSentUpdate/{id:guid}")]
    public async Task<IActionResult> PackageSentUpdate(Guid id)
    {
        var viewModel = new PackageSentUpdateViewModels
        {
            Package = await _packageSent.GetById(id),
            Receivers = _receiverService.GetAll(),
            Foods = _foodService.GetAll()
        };

        return View(viewModel);
    }

    [HttpGet("PackageSentDelete/{id}")]
    public async Task<IActionResult> PackageSentDelete(Guid id)
    {
        await _packageSent.Delete(id);

        return RedirectToAction("ProjectPackages", "Project");
    }


    [HttpPost("PackageSentNew")]
    public async Task<IActionResult> PackageSentNew(PackageSentResponseViewModels formViewModel)
    {
        var dto = new PackageSentRequestDto
        {
            FoodList = formViewModel.SelectedFoods,
            ReceiverId = formViewModel.ReceiverId
        };

        await _packageSent.Insert(dto);

        TempData["ConfirmationMessage"] = "PackageSent created successfully";
        return RedirectToAction("ProjectPackages", "Project");
    }

    [HttpPost("PackageSentUpdated")]
    public async Task<IActionResult> PackageSentUpdated(PackageSentResponseViewModels formViewModel)
    {
        var dto = new PackageSentRequestDto
        {
            FoodList = formViewModel.SelectedFoods,
            ReceiverId = formViewModel.ReceiverId
        };
        var id = formViewModel.Id;
        await _packageSent.Edit(id, dto);

        TempData["ConfirmationMessage"] = "PackageSent created successfully";

        return RedirectToAction("ProjectPackages", "Project");
    }
}

src/Presentation/Controllers/ProjectController.cs
using System.Diagnostics;
using Application.Interfaces.Food;
using Application.Interfaces.Package;
using Application.Interfaces.ThirdParty;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;

namespace Presentation.Controllers;

public class ProjectController : Controller
{
    private readonly IDonorService _donorService;
    private readonly IFoodService _foodService;
    private readonly IPackageReceivedService _packageReceivedService;
    private readonly IPackageSentService _packageSentService;
    private readonly IReceiverService _receiverService;

    public ProjectController(
        IDonorService donorService, IReceiverService receiverService,
        IFoodService foodService, IPackageReceivedService packageReceivedService,
        IPackageSentService packageSentService)
    {
        _donorService = donorService;
        _receiverService = receiverService;
        _foodService = foodService;
        _packageReceivedService = packageReceivedService;
        _packageSentService = packageSentService;
    }

    [HttpGet("/projectentities")]
    public IActionResult ProjectEntities()
    {
        var viewModel = new ProjectEntitiesViewModel
        {
            Donors = _donorService.GetAll(),
            Receivers = _receiverService.GetAll(),
            Foods = _foodService.GetAll()
        };

        return View(viewModel);
    }

    [HttpGet("/projectpackages")]
    public IActionResult ProjectPackages()
    {
        var viewModel = new ProjectPackagesViewModel
        {
            Donors = _donorService.GetAll(),
            Receivers = _receiverService.GetAll(),
            Foods = _foodService.GetAll(),
            PackagesReceived = _packageReceivedService.GetAll(),
            PackagesSent = _packageSentService.GetAll()
        };

        return View(viewModel);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/Presentation/Controllers/ReceiverController.cs
using Application.Dtos.ThirdPartyDtos;
using Application.Interfaces.ThirdParty;
using Domain.Entities.ThirdPartyRegister;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models.ReceiverModels;

namespace Presentation.Controllers;

public class ReceiverController : Controller
{
    private readonly IReceiverService _receiverService;

    public ReceiverController(IReceiverService receiverService)
    {
        _receiverService = receiverService;
    }

    [HttpGet("/ReceiverCreate")]
    public IActionResult ReceiverCreate()
    {
        return View();
    }

    [HttpGet("ReceiverUpdate/{id:guid}")]
    public async Task<IActionResult> ReceiverUpdate(Guid id)
    {
        var viewModel = await _receiverService.GetById(id);

        return View(viewModel);
    }

    [HttpGet("ReceiverDelete/{id:guid}")]
    public async Task<IActionResult> ReceiverDelete(Guid id)
    {
        await _receiverService.Delete(id);

        return RedirectToAction("ProjectEntities", "Project");
    }


    [HttpPost("ReceiverNew")]
    public async Task<IActionResult> ReceiverNew(ReceiverFormViewModel formViewModel)
    {
        var dto = new ReceiverRequestDto
        {
            Name = new ThirdPartyName(formViewModel.Name!),
            IsCompany = formViewModel.IsCompany
        };

        await _receiverService.Insert(dto);

        TempData["ConfirmationMessage"] = "Receiver created successfully";

        return RedirectToAction("ProjectEntities", "Project");
    }

    [HttpPost("ReceiverUpdated")]
    public async Task<IActionResult> ReceiverUpdated(ReceiverFormViewModel formViewModel)
    {
        var dto = new ReceiverRequestDto
        {
            Name = new ThirdPartyName(formViewModel.Name!),
            IsCompany = formViewModel.IsCompany
        };
        var id = formViewModel.Id;
        await _receiverService.Edit(id, dto);

        TempData["ConfirmationMessage"] = "Receiver created successfully";
        return RedirectToAction("ProjectEntities", "Project");
    }
}

src/Presentation/Views/Project/ProjectEntities.cshtml
@{
    ViewData["Title"] = "The Project";
}
@model ProjectEntitiesViewModel

<div>
    <h1 class="text-center pb-1">E N T I T I E S</h1>
    <h3 class="text-center pb-1">
        <a asp-controller="Project" asp-action="ProjectEntities" class="btn btn-secondary btn-lg disabled">..:: Entities ::..</a>
        <a asp-controller="Project" asp-action="ProjectPackages" class="btn btn-success btn-lg">..:: Packages ::..</a>
    </h3>

    <hr/>

    <h4>Donors</h4>
    <div class="container bg-light pt-2">
        <a asp-controller="Donor" asp-action="DonorCreate" class="btn btn-outline-success btn-lg d-block">Create</a>

        <table class="table w-50">
            <thead>
            <tr>
                <th>Name</th>
                <th>Is Company?</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.Donors!)
            {
                <tr>
                    <td>@item.Name.Name</td>
                    <td>@(item.IsCompany ? "Yes" : "No")</td>
                    <td>
                        <a asp-controller="Donor" asp-action="DonorUpdate" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Edit</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <hr/>

    <h4>Receivers</h4>
    <div class="container bg-light pt-2">
        <a asp-controller="Receiver" asp-action="ReceiverCreate" class="btn btn-outline-success btn-lg d-block">Create</a>

        <table class="table w-50">
            <thead>
            <tr>
                <th>Name</th>
                <th>Is Company?</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.Receivers!)
            {
                <tr>
                    <td>@item.Name.Name</td>
                    <td>@(item.IsCompany ? "Yes" : "No")</td>
                    <td>
                        <a asp-controller="Receiver" asp-action="ReceiverUpdate" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Edit</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <hr/>

    <h4>Food</h4>
    <div class="container bg-light pt-2">
        <a asp-controller="Food" asp-action="FoodCreate" class="btn btn-outline-success btn-lg d-block">Create</a>

        <table class="table w-75">
            <thead>
            <tr>
                <th>Name</th>
                <th>State</th>
                <th>Expiration Date</th>
                <th>Is Company?</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.Foods!)
            {
                <tr>
                    <td>@item.FoodName.Name</td>
                    <td>@item.State</td>
                    <td>@item.ExpirationDate.ToString("dd/MM/yyyy")</td>
                    <td>@(item.IsPerishable ? "Yes" : "No")</td>
                    <td>
                        <a asp-controller="Food" asp-action="FoodUpdate" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Edit</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
        <hr/>
    </div>
</div>

src/Presentation/Views/Project/ProjectPackages.cshtml
@{
    ViewData["Title"] = "The Project";
}
@model ProjectPackagesViewModel

<div>
    <h1 class="text-center pb-1">P A C K A G E S</h1>
    <h3 class="text-center pb-1">
        <a asp-controller="Project" asp-action="ProjectEntities" class="btn btn-success btn-lg">..:: Entities ::..</a>
        <a asp-controller="Project" asp-action="ProjectPackages" class="btn btn-secondary btn-lg disabled">..:: Packages ::..</a>
    </h3>

    <hr/>

    <h4>Packages we received</h4>
    <div class="container bg-light pt-2">
        <a asp-controller="PackageReceived" asp-action="PackageReceivedCreate" class="btn btn-outline-success btn-lg d-block">Create</a>

        <table class="table w-50">
            <thead>
            <tr>
                <th>Name</th>
                <th>Food List</th>
                <th>Date</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.PackagesReceived!)
            {
                var donorName = Model.Donors!.FirstOrDefault(d => d.Id == item.DonorId);
                <tr>
                    <td>
                        @if (donorName != null)
                        {
                            @donorName.Name.Name
                        }
                        else
                        {
                            <text>Unknown Donor</text>
                        }
                    </td>
                    <td>
                        @foreach (var foodId in item.FoodList)
                        {
                            var foodName = Model.Foods!.FirstOrDefault(f => f.Id == foodId)?.FoodName.Name;

                            if (foodName != null)
                            {
                                <span>@foodName </span>
                                <br/>
                            }
                        }
                    </td>
                    <td>@item.PackageCreation.ToString("dd/MM/yyyy")</td>
                    <td>
                        <a asp-controller="PackageReceived" asp-action="PackageReceivedUpdate" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Edit</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <hr/>

    <h4>Packages we sent</h4>
    <div class="container bg-light pt-2">
        <a asp-controller="PackageSent" asp-action="PackageSentCreate" class="btn btn-outline-success btn-lg d-block">Create</a>
        <table class="table w-50">
            <thead>
            <tr>
                <th>Name</th>
                <th>Food List</th>
                <th>Date</th>
                <th>Edit</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.PackagesSent!)
            {
                var receiverName = Model.Receivers!.FirstOrDefault(d => d.Id == item.ReceiverId);
                <tr>
                    <td>@receiverName!.Name.Name</td>
                    <td>
                        @foreach (var foodId in item.FoodList)
                        {
                            var foodName = Model.Foods!.FirstOrDefault(f => f.Id == foodId)?.FoodName.Name;

                            if (foodName != null)
                            {
                                <span>@foodName </span>
                                <br/>
                            }
                        }
                    </td>
                    <td>@item.PackageCreation.ToString("dd/MM/yyyy")</td>
                    <td>
                        <a asp-controller="PackageSent" asp-action="PackageSentUpdate" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Edit</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
    <hr/>
</div>