src/Presentation/Models/PackageReceivedModels/PackageReceivedUpdateViewModels.cs
using Application.Dtos.FoodDtos;
using Application.Dtos.PackageDtos;
using Application.Dtos.ThirdPartyDtos;

namespace Presentation.Models.PackageReceivedModels;

public class PackageReceivedUpdateViewModels
{
    public PackageReceivedResponseDto? Package { get; set; }
    public IEnumerable<DonorResponseDto>? Donors { get; set; }
    public IEnumerable<FoodResponseDto>? Foods { get; set; }
}

src/Presentation/Models/PackageReceivedModels/PackageReceivedViewModels.cs
using Application.Dtos.FoodDtos;
using Application.Dtos.PackageDtos;
using Application.Dtos.ThirdPartyDtos;

namespace Presentation.Models.PackageReceivedModels;

public class PackageReceivedViewModels
{
    public IEnumerable<PackageReceivedResponseDto>? Packages { get; set; }
    public IEnumerable<DonorResponseDto>? Donors { get; set; }
    public IEnumerable<FoodResponseDto>? Foods { get; set; }
}

src/Presentation/Controllers/PackageReceivedController.cs
using Application.Dtos.PackageDtos;
using Application.Interfaces.Food;
using Application.Interfaces.Package;
using Application.Interfaces.ThirdParty;
using Microsoft.AspNetCore.Mvc;
using Presentation.Models.PackageReceivedModels;

namespace Presentation.Controllers;

public class PackageReceivedController : Controller
{
    private readonly IDonorService _donorService;
    private readonly IFoodService _foodService;
    private readonly IPackageReceivedService _packageReceived;

    public PackageReceivedController(IPackageReceivedService packageReceivedService, IDonorService donorService,
        IFoodService foodService)
    {
        _packageReceived = packageReceivedService;
        _donorService = donorService;
        _foodService = foodService;
    }

    [HttpGet("/PackageReceivedCreate")]
    public IActionResult PackageReceivedCreate()
    {
        var viewModel = new PackageReceivedViewModels
        {
            Donors = _donorService.GetAll(),
            Foods = _foodService.GetAll()
        };
        return View(viewModel);
    }

    [HttpGet("PackageReceivedUpdate/{id:guid}")]
    public async Task<IActionResult> PackageReceivedUpdate(Guid id)
    {
        var viewModel = new PackageReceivedUpdateViewModels
        {
            Package = await _packageReceived.GetById(id),
            Donors = _donorService.GetAll(),
            Foods = _foodService.GetAll()
        };

        return View(viewModel);
    }

    [HttpGet("PackageReceivedDelete/{id}")]
    public async Task<IActionResult> PackageReceivedDelete(Guid id)
    {
        await _packageReceived.Delete(id);

        return RedirectToAction("ProjectPackages", "Project");
    }


    [HttpPost("PackageReceivedNew")]
    public async Task<IActionResult> PackageReceivedNew(PackageReceivedResponseViewModels formViewModel)
    {
        var dto = new PackageReceivedRequestDto
        {
            FoodList = formViewModel.SelectedFoods,
            DonorId = formViewModel.DonorId
        };

        await _packageReceived.Insert(dto);

        TempData["ConfirmationMessage"] = "PackageReceived created successfully";
        return RedirectToAction("ProjectPackages", "Project");
    }

    [HttpPost("PackageReceivedUpdated")]
    public async Task<IActionResult> PackageReceivedUpdated(PackageReceivedResponseViewModels formViewModel)
    {
        var dto = new PackageReceivedRequestDto
        {
            FoodList = formViewModel.SelectedFoods,
            DonorId = formViewModel.DonorId
        };
        var id = formViewModel.Id;
        await _packageReceived.Edit(id, dto);

        TempData["ConfirmationMessage"] = "PackageReceived created successfully";

        return RedirectToAction("ProjectPackages", "Project");
    }
}

src/Presentation/Views/PackageReceived/PackageReceivedCreate.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Presentation.Models.PackageReceivedModels.PackageReceivedViewModels
<div>
    <h3 class="text-center pb-1">PACKAGE - R E C E I V E D - </h3>
    <hr/>

    <div class="container">
        <form asp-controller="PackageReceived" asp-action="PackageReceivedNew" method="post">
            <fieldset>
                <legend>Add/Edit Package Received</legend>
                <table class="table w-50">
                    <tr>
                        <td>
                            <label for="DonorId">Donor: </label>
                            <select id="DonorId" name="DonorId" class="form-control" required>
                                @if (Model.Donors != null)
                                {
                                    foreach (var option in Model.Donors)
                                    {
                                        <option value="@option.Id">@option.Name.Name</option>
                                    }
                                }
                            </select>

                        </td>
                    </tr>
                    <tr>
                        <td>
                            @if (Model.Foods != null)
                            {
                                foreach (var option in Model.Foods)
                                {
                                    <input type="checkbox" id="@option.Id" name="SelectedFoods" value="@option.Id">
                                    <label for="@option.Id"> @option.FoodName.Name</label>
                                    <br>
                                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            @Html.AntiForgeryToken()
                            <input type="submit" value=" - S A V E - " class="btn btn-secondary" style="width: 100%;"/>
                        </td>
                    </tr>
                </table>
            </fieldset>
        </form>
    </div>
    <hr/>
</div>

src/Presentation/Views/PackageReceived/PackageReceivedUpdate.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Presentation.Models.PackageReceivedModels.PackageReceivedUpdateViewModels
<div>
    <h3 class="text-center pb-1">PACKAGE - R E C E I V E D - </h3>
    <hr/>

    <div class="container">
        <form asp-controller="PackageReceived" asp-action="PackageReceivedUpdated" method="post">
            <input type="hidden" name="Id" value="@Model.Package!.Id"/>
            <fieldset>
                <legend>Add/Edit Package Received</legend>
                <table class="table w-50">
                    <tr>
                        <td>
                            <label for="DonorId">Donor: </label>
                            <select id="DonorId" name="DonorId" class="form-control" required>
                                @if (Model.Donors != null)
                                {
                                    foreach (var option in Model.Donors)
                                    {
                                        if (Model.Package.DonorId == option.Id)
                                        {
                                            <option value="@option.Id" selected="selected">@option.Name.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@option.Id">@option.Name.Name</option>
                                        }
                                    }
                                }
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @if (Model.Foods != null)
                            {
                                foreach (var option in Model.Foods)
                                {
                                    var isChecked = Model.Package.FoodList.Contains(option.Id);
                                    <input type="checkbox" id="@option.Id" name="SelectedFoods" value="@option.Id" @(isChecked ? "checked" : "")>
                                    <label for="@option.Id"> @option.FoodName.Name</label>
                                    <br>
                                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            @Html.AntiForgeryToken()
                            <input type="submit" value=" - S A V E - " class="btn btn-secondary" style="width: 100%;"/>
                            <a asp-controller="PackageReceived" asp-action="PackageReceivedDelete" asp-route-id="@Model.Package.Id" class="btn btn-danger mt-1" style="width: 100%;">
                                - D E L E T E -
                            </a>
                        </td>
                    </tr>
                </table>
            </fieldset>
        </form>
    </div>
    <hr/>
</div>